// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: event_logs.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const createEventLog = `-- name: CreateEventLog :one
INSERT INTO event_logs (
  resource_id,
  occurred_at,
  event_type,
  severity,
  message,
  rule_id,
  profile_id,
  metadata,
  request_id,
  client_ip,
  method,
  path
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, resource_id, occurred_at, event_type, severity, message, rule_id, profile_id, metadata, request_id, client_ip, method, path
`

type CreateEventLogParams struct {
	ResourceID int64                 `json:"resource_id"`
	OccurredAt time.Time             `json:"occurred_at"`
	EventType  string                `json:"event_type"`
	Severity   string                `json:"severity"`
	Message    string                `json:"message"`
	RuleID     sql.NullInt64         `json:"rule_id"`
	ProfileID  sql.NullInt64         `json:"profile_id"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	RequestID  sql.NullString        `json:"request_id"`
	ClientIp   sql.NullString        `json:"client_ip"`
	Method     sql.NullString        `json:"method"`
	Path       sql.NullString        `json:"path"`
}

func (q *Queries) CreateEventLog(ctx context.Context, arg CreateEventLogParams) (EventLog, error) {
	row := q.db.QueryRowContext(ctx, createEventLog,
		arg.ResourceID,
		arg.OccurredAt,
		arg.EventType,
		arg.Severity,
		arg.Message,
		arg.RuleID,
		arg.ProfileID,
		arg.Metadata,
		arg.RequestID,
		arg.ClientIp,
		arg.Method,
		arg.Path,
	)
	var i EventLog
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.OccurredAt,
		&i.EventType,
		&i.Severity,
		&i.Message,
		&i.RuleID,
		&i.ProfileID,
		&i.Metadata,
		&i.RequestID,
		&i.ClientIp,
		&i.Method,
		&i.Path,
	)
	return i, err
}

const getEventLog = `-- name: GetEventLog :one
SELECT id, resource_id, occurred_at, event_type, severity, message, rule_id, profile_id, metadata, request_id, client_ip, method, path
FROM event_logs
WHERE id = $1
`

func (q *Queries) GetEventLog(ctx context.Context, id int64) (EventLog, error) {
	row := q.db.QueryRowContext(ctx, getEventLog, id)
	var i EventLog
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.OccurredAt,
		&i.EventType,
		&i.Severity,
		&i.Message,
		&i.RuleID,
		&i.ProfileID,
		&i.Metadata,
		&i.RequestID,
		&i.ClientIp,
		&i.Method,
		&i.Path,
	)
	return i, err
}

const listEventLogs = `-- name: ListEventLogs :many
SELECT id, resource_id, occurred_at, event_type, severity, message, rule_id, profile_id, metadata, request_id, client_ip, method, path
FROM event_logs
ORDER BY id
`

func (q *Queries) ListEventLogs(ctx context.Context) ([]EventLog, error) {
	rows, err := q.db.QueryContext(ctx, listEventLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.OccurredAt,
			&i.EventType,
			&i.Severity,
			&i.Message,
			&i.RuleID,
			&i.ProfileID,
			&i.Metadata,
			&i.RequestID,
			&i.ClientIp,
			&i.Method,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
