// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: ml_models.sql

package db

import (
	"context"
)

const createMLModel = `-- name: CreateMLModel :one
INSERT INTO ml_models (name, model_data)
VALUES ($1, $2)
RETURNING id, name, model_data
`

type CreateMLModelParams struct {
	Name      string `json:"name"`
	ModelData []byte `json:"model_data"`
}

func (q *Queries) CreateMLModel(ctx context.Context, arg CreateMLModelParams) (MlModel, error) {
	row := q.db.QueryRowContext(ctx, createMLModel, arg.Name, arg.ModelData)
	var i MlModel
	err := row.Scan(&i.ID, &i.Name, &i.ModelData)
	return i, err
}

const deleteMLModel = `-- name: DeleteMLModel :one
DELETE FROM ml_models
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteMLModel(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteMLModel, id)
	err := row.Scan(&id)
	return id, err
}

const getMLModel = `-- name: GetMLModel :one
SELECT id, name, model_data
FROM ml_models
WHERE id = $1
`

func (q *Queries) GetMLModel(ctx context.Context, id int64) (MlModel, error) {
	row := q.db.QueryRowContext(ctx, getMLModel, id)
	var i MlModel
	err := row.Scan(&i.ID, &i.Name, &i.ModelData)
	return i, err
}

const listMLModels = `-- name: ListMLModels :many
SELECT id, name, model_data
FROM ml_models
ORDER BY id
`

func (q *Queries) ListMLModels(ctx context.Context) ([]MlModel, error) {
	rows, err := q.db.QueryContext(ctx, listMLModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MlModel{}
	for rows.Next() {
		var i MlModel
		if err := rows.Scan(&i.ID, &i.Name, &i.ModelData); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMLModel = `-- name: UpdateMLModel :one
UPDATE ml_models
SET name = $2,
    model_data = $3
WHERE id = $1
RETURNING id, name, model_data
`

type UpdateMLModelParams struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	ModelData []byte `json:"model_data"`
}

func (q *Queries) UpdateMLModel(ctx context.Context, arg UpdateMLModelParams) (MlModel, error) {
	row := q.db.QueryRowContext(ctx, updateMLModel, arg.ID, arg.Name, arg.ModelData)
	var i MlModel
	err := row.Scan(&i.ID, &i.Name, &i.ModelData)
	return i, err
}
