// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type EventLog struct {
	ID         int64                 `json:"id"`
	ResourceID int64                 `json:"resource_id"`
	OccurredAt time.Time             `json:"occurred_at"`
	EventType  string                `json:"event_type"`
	Severity   string                `json:"severity"`
	Message    string                `json:"message"`
	RuleID     sql.NullInt64         `json:"rule_id"`
	ProfileID  sql.NullInt64         `json:"profile_id"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	RequestID  sql.NullString        `json:"request_id"`
	ClientIp   sql.NullString        `json:"client_ip"`
	Method     sql.NullString        `json:"method"`
	Path       sql.NullString        `json:"path"`
}

type MlModel struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	ModelData []byte `json:"model_data"`
}

type RequestLog struct {
	ID                   int64                 `json:"id"`
	ResourceID           sql.NullInt64         `json:"resource_id"`
	OccurredAt           time.Time             `json:"occurred_at"`
	ClientIp             string                `json:"client_ip"`
	Method               string                `json:"method"`
	Path                 string                `json:"path"`
	StatusCode           int32                 `json:"status_code"`
	Action               string                `json:"action"`
	RuleID               sql.NullInt64         `json:"rule_id"`
	ProfileID            sql.NullInt64         `json:"profile_id"`
	UserAgent            sql.NullString        `json:"user_agent"`
	Country              sql.NullString        `json:"country"`
	LatencyMs            sql.NullInt32         `json:"latency_ms"`
	RequestID            sql.NullString        `json:"request_id"`
	Metadata             pqtype.NullRawMessage `json:"metadata"`
	Host                 sql.NullString        `json:"host"`
	Scheme               sql.NullString        `json:"scheme"`
	Protocol             sql.NullString        `json:"protocol"`
	Authority            sql.NullString        `json:"authority"`
	Query                sql.NullString        `json:"query"`
	SourcePort           sql.NullInt32         `json:"source_port"`
	DestinationIp        sql.NullString        `json:"destination_ip"`
	DestinationPort      sql.NullInt32         `json:"destination_port"`
	SourcePrincipal      sql.NullString        `json:"source_principal"`
	RequestHeaders       pqtype.NullRawMessage `json:"request_headers"`
	RequestBodySize      sql.NullInt32         `json:"request_body_size"`
	RequestHttpID        sql.NullString        `json:"request_http_id"`
	Fragment             sql.NullString        `json:"fragment"`
	RequestBody          sql.NullString        `json:"request_body"`
	SourceService        sql.NullString        `json:"source_service"`
	SourceLabels         pqtype.NullRawMessage `json:"source_labels"`
	DestinationService   sql.NullString        `json:"destination_service"`
	DestinationLabels    pqtype.NullRawMessage `json:"destination_labels"`
	ContextExtensions    pqtype.NullRawMessage `json:"context_extensions"`
	MetadataContext      pqtype.NullRawMessage `json:"metadata_context"`
	RouteMetadataContext pqtype.NullRawMessage `json:"route_metadata_context"`
}

type Resource struct {
	ID                int64         `json:"id"`
	Name              string        `json:"name"`
	UrlPattern        string        `json:"url_pattern"`
	SecurityProfileID sql.NullInt64 `json:"security_profile_id"`
	TrafficProfileID  sql.NullInt64 `json:"traffic_profile_id"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
}

type SecurityProfile struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	BaseAction  string         `json:"base_action"`
	LogEnabled  bool           `json:"log_enabled"`
	IsEnabled   bool           `json:"is_enabled"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type SecurityRule struct {
	ID          int64                 `json:"id"`
	ProfileID   int64                 `json:"profile_id"`
	Name        string                `json:"name"`
	Description sql.NullString        `json:"description"`
	Priority    int32                 `json:"priority"`
	RuleType    string                `json:"rule_type"`
	Action      string                `json:"action"`
	Conditions  pqtype.NullRawMessage `json:"conditions"`
	DryRun      bool                  `json:"dry_run"`
	IsEnabled   bool                  `json:"is_enabled"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
	MlModelID   sql.NullInt64         `json:"ml_model_id"`
	MlThreshold sql.NullInt16         `json:"ml_threshold"`
}

type TrafficProfile struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsEnabled   bool           `json:"is_enabled"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type TrafficRule struct {
	ID            int64                 `json:"id"`
	ProfileID     int64                 `json:"profile_id"`
	Name          string                `json:"name"`
	Description   sql.NullString        `json:"description"`
	Priority      int32                 `json:"priority"`
	DryRun        bool                  `json:"dry_run"`
	MatchAll      bool                  `json:"match_all"`
	RequestsLimit int32                 `json:"requests_limit"`
	PeriodSeconds int32                 `json:"period_seconds"`
	Conditions    pqtype.NullRawMessage `json:"conditions"`
	IsEnabled     bool                  `json:"is_enabled"`
	CreatedAt     time.Time             `json:"created_at"`
	UpdatedAt     time.Time             `json:"updated_at"`
}
