// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateEventLog(ctx context.Context, arg CreateEventLogParams) (EventLog, error)
	CreateMLModel(ctx context.Context, arg CreateMLModelParams) (MlModel, error)
	CreateRequestLog(ctx context.Context, arg CreateRequestLogParams) (CreateRequestLogRow, error)
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	CreateSecurityProfile(ctx context.Context, arg CreateSecurityProfileParams) (SecurityProfile, error)
	CreateSecurityRule(ctx context.Context, arg CreateSecurityRuleParams) (CreateSecurityRuleRow, error)
	CreateTrafficProfile(ctx context.Context, arg CreateTrafficProfileParams) (TrafficProfile, error)
	CreateTrafficRule(ctx context.Context, arg CreateTrafficRuleParams) (TrafficRule, error)
	DeleteMLModel(ctx context.Context, id int64) (int64, error)
	DeleteResource(ctx context.Context, id int64) (int64, error)
	DeleteSecurityProfile(ctx context.Context, id int64) (int64, error)
	DeleteSecurityRule(ctx context.Context, id int64) (int64, error)
	DeleteTrafficProfile(ctx context.Context, id int64) (int64, error)
	DeleteTrafficRule(ctx context.Context, id int64) (int64, error)
	GetEventLog(ctx context.Context, id int64) (EventLog, error)
	GetMLModel(ctx context.Context, id int64) (MlModel, error)
	GetRequestLog(ctx context.Context, id int64) (GetRequestLogRow, error)
	GetResource(ctx context.Context, id int64) (Resource, error)
	GetSecurityProfile(ctx context.Context, id int64) (SecurityProfile, error)
	GetSecurityRule(ctx context.Context, id int64) (GetSecurityRuleRow, error)
	GetTrafficProfile(ctx context.Context, id int64) (TrafficProfile, error)
	GetTrafficRule(ctx context.Context, id int64) (TrafficRule, error)
	ListEventLogs(ctx context.Context) ([]EventLog, error)
	ListMLModels(ctx context.Context) ([]MlModel, error)
	ListRequestLogs(ctx context.Context) ([]ListRequestLogsRow, error)
	ListResources(ctx context.Context) ([]Resource, error)
	ListSecurityProfiles(ctx context.Context) ([]SecurityProfile, error)
	ListSecurityRules(ctx context.Context) ([]ListSecurityRulesRow, error)
	ListTrafficProfiles(ctx context.Context) ([]TrafficProfile, error)
	ListTrafficRules(ctx context.Context) ([]TrafficRule, error)
	UpdateMLModel(ctx context.Context, arg UpdateMLModelParams) (MlModel, error)
	UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error)
	UpdateSecurityProfile(ctx context.Context, arg UpdateSecurityProfileParams) (SecurityProfile, error)
	UpdateSecurityRule(ctx context.Context, arg UpdateSecurityRuleParams) (UpdateSecurityRuleRow, error)
	UpdateTrafficProfile(ctx context.Context, arg UpdateTrafficProfileParams) (TrafficProfile, error)
	UpdateTrafficRule(ctx context.Context, arg UpdateTrafficRuleParams) (TrafficRule, error)
}

var _ Querier = (*Queries)(nil)
