// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: request_logs.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const createRequestLog = `-- name: CreateRequestLog :one
INSERT INTO request_logs (
  resource_id,
  occurred_at,
  client_ip,
  method,
  path,
  status_code,
  action,
  rule_id,
  profile_id,
  user_agent,
  country,
  latency_ms,
  request_id,
  metadata,
  host,
  scheme,
  protocol,
  authority,
  query,
  source_port,
  destination_ip,
  destination_port,
  source_principal,
  source_service,
  source_labels,
  destination_service,
  destination_labels,
  request_http_id,
  fragment,
  request_headers,
  request_body_size,
  request_body,
  context_extensions,
  metadata_context,
  route_metadata_context
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
  $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
  $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35
)
RETURNING id, resource_id, occurred_at, client_ip, method, path, status_code, action, rule_id, profile_id, user_agent, country, latency_ms, request_id, metadata, host, scheme, protocol, authority, query, source_port, destination_ip, destination_port, source_principal, source_service, source_labels, destination_service, destination_labels, request_http_id, fragment, request_headers, request_body_size, request_body, context_extensions, metadata_context, route_metadata_context
`

type CreateRequestLogParams struct {
	ResourceID           sql.NullInt64         `json:"resource_id"`
	OccurredAt           time.Time             `json:"occurred_at"`
	ClientIp             string                `json:"client_ip"`
	Method               string                `json:"method"`
	Path                 string                `json:"path"`
	StatusCode           int32                 `json:"status_code"`
	Action               string                `json:"action"`
	RuleID               sql.NullInt64         `json:"rule_id"`
	ProfileID            sql.NullInt64         `json:"profile_id"`
	UserAgent            sql.NullString        `json:"user_agent"`
	Country              sql.NullString        `json:"country"`
	LatencyMs            sql.NullInt32         `json:"latency_ms"`
	RequestID            sql.NullString        `json:"request_id"`
	Metadata             pqtype.NullRawMessage `json:"metadata"`
	Host                 sql.NullString        `json:"host"`
	Scheme               sql.NullString        `json:"scheme"`
	Protocol             sql.NullString        `json:"protocol"`
	Authority            sql.NullString        `json:"authority"`
	Query                sql.NullString        `json:"query"`
	SourcePort           sql.NullInt32         `json:"source_port"`
	DestinationIp        sql.NullString        `json:"destination_ip"`
	DestinationPort      sql.NullInt32         `json:"destination_port"`
	SourcePrincipal      sql.NullString        `json:"source_principal"`
	SourceService        sql.NullString        `json:"source_service"`
	SourceLabels         pqtype.NullRawMessage `json:"source_labels"`
	DestinationService   sql.NullString        `json:"destination_service"`
	DestinationLabels    pqtype.NullRawMessage `json:"destination_labels"`
	RequestHttpID        sql.NullString        `json:"request_http_id"`
	Fragment             sql.NullString        `json:"fragment"`
	RequestHeaders       pqtype.NullRawMessage `json:"request_headers"`
	RequestBodySize      sql.NullInt32         `json:"request_body_size"`
	RequestBody          sql.NullString        `json:"request_body"`
	ContextExtensions    pqtype.NullRawMessage `json:"context_extensions"`
	MetadataContext      pqtype.NullRawMessage `json:"metadata_context"`
	RouteMetadataContext pqtype.NullRawMessage `json:"route_metadata_context"`
}

type CreateRequestLogRow struct {
	ID                   int64                 `json:"id"`
	ResourceID           sql.NullInt64         `json:"resource_id"`
	OccurredAt           time.Time             `json:"occurred_at"`
	ClientIp             string                `json:"client_ip"`
	Method               string                `json:"method"`
	Path                 string                `json:"path"`
	StatusCode           int32                 `json:"status_code"`
	Action               string                `json:"action"`
	RuleID               sql.NullInt64         `json:"rule_id"`
	ProfileID            sql.NullInt64         `json:"profile_id"`
	UserAgent            sql.NullString        `json:"user_agent"`
	Country              sql.NullString        `json:"country"`
	LatencyMs            sql.NullInt32         `json:"latency_ms"`
	RequestID            sql.NullString        `json:"request_id"`
	Metadata             pqtype.NullRawMessage `json:"metadata"`
	Host                 sql.NullString        `json:"host"`
	Scheme               sql.NullString        `json:"scheme"`
	Protocol             sql.NullString        `json:"protocol"`
	Authority            sql.NullString        `json:"authority"`
	Query                sql.NullString        `json:"query"`
	SourcePort           sql.NullInt32         `json:"source_port"`
	DestinationIp        sql.NullString        `json:"destination_ip"`
	DestinationPort      sql.NullInt32         `json:"destination_port"`
	SourcePrincipal      sql.NullString        `json:"source_principal"`
	SourceService        sql.NullString        `json:"source_service"`
	SourceLabels         pqtype.NullRawMessage `json:"source_labels"`
	DestinationService   sql.NullString        `json:"destination_service"`
	DestinationLabels    pqtype.NullRawMessage `json:"destination_labels"`
	RequestHttpID        sql.NullString        `json:"request_http_id"`
	Fragment             sql.NullString        `json:"fragment"`
	RequestHeaders       pqtype.NullRawMessage `json:"request_headers"`
	RequestBodySize      sql.NullInt32         `json:"request_body_size"`
	RequestBody          sql.NullString        `json:"request_body"`
	ContextExtensions    pqtype.NullRawMessage `json:"context_extensions"`
	MetadataContext      pqtype.NullRawMessage `json:"metadata_context"`
	RouteMetadataContext pqtype.NullRawMessage `json:"route_metadata_context"`
}

func (q *Queries) CreateRequestLog(ctx context.Context, arg CreateRequestLogParams) (CreateRequestLogRow, error) {
	row := q.db.QueryRowContext(ctx, createRequestLog,
		arg.ResourceID,
		arg.OccurredAt,
		arg.ClientIp,
		arg.Method,
		arg.Path,
		arg.StatusCode,
		arg.Action,
		arg.RuleID,
		arg.ProfileID,
		arg.UserAgent,
		arg.Country,
		arg.LatencyMs,
		arg.RequestID,
		arg.Metadata,
		arg.Host,
		arg.Scheme,
		arg.Protocol,
		arg.Authority,
		arg.Query,
		arg.SourcePort,
		arg.DestinationIp,
		arg.DestinationPort,
		arg.SourcePrincipal,
		arg.SourceService,
		arg.SourceLabels,
		arg.DestinationService,
		arg.DestinationLabels,
		arg.RequestHttpID,
		arg.Fragment,
		arg.RequestHeaders,
		arg.RequestBodySize,
		arg.RequestBody,
		arg.ContextExtensions,
		arg.MetadataContext,
		arg.RouteMetadataContext,
	)
	var i CreateRequestLogRow
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.OccurredAt,
		&i.ClientIp,
		&i.Method,
		&i.Path,
		&i.StatusCode,
		&i.Action,
		&i.RuleID,
		&i.ProfileID,
		&i.UserAgent,
		&i.Country,
		&i.LatencyMs,
		&i.RequestID,
		&i.Metadata,
		&i.Host,
		&i.Scheme,
		&i.Protocol,
		&i.Authority,
		&i.Query,
		&i.SourcePort,
		&i.DestinationIp,
		&i.DestinationPort,
		&i.SourcePrincipal,
		&i.SourceService,
		&i.SourceLabels,
		&i.DestinationService,
		&i.DestinationLabels,
		&i.RequestHttpID,
		&i.Fragment,
		&i.RequestHeaders,
		&i.RequestBodySize,
		&i.RequestBody,
		&i.ContextExtensions,
		&i.MetadataContext,
		&i.RouteMetadataContext,
	)
	return i, err
}

const getRequestLog = `-- name: GetRequestLog :one
SELECT id, resource_id, occurred_at, client_ip, method, path, status_code, action, rule_id, profile_id, user_agent, country, latency_ms, request_id, metadata, host, scheme, protocol, authority, query, source_port, destination_ip, destination_port, source_principal, source_service, source_labels, destination_service, destination_labels, request_http_id, fragment, request_headers, request_body_size, request_body, context_extensions, metadata_context, route_metadata_context
FROM request_logs
WHERE id = $1
`

type GetRequestLogRow struct {
	ID                   int64                 `json:"id"`
	ResourceID           sql.NullInt64         `json:"resource_id"`
	OccurredAt           time.Time             `json:"occurred_at"`
	ClientIp             string                `json:"client_ip"`
	Method               string                `json:"method"`
	Path                 string                `json:"path"`
	StatusCode           int32                 `json:"status_code"`
	Action               string                `json:"action"`
	RuleID               sql.NullInt64         `json:"rule_id"`
	ProfileID            sql.NullInt64         `json:"profile_id"`
	UserAgent            sql.NullString        `json:"user_agent"`
	Country              sql.NullString        `json:"country"`
	LatencyMs            sql.NullInt32         `json:"latency_ms"`
	RequestID            sql.NullString        `json:"request_id"`
	Metadata             pqtype.NullRawMessage `json:"metadata"`
	Host                 sql.NullString        `json:"host"`
	Scheme               sql.NullString        `json:"scheme"`
	Protocol             sql.NullString        `json:"protocol"`
	Authority            sql.NullString        `json:"authority"`
	Query                sql.NullString        `json:"query"`
	SourcePort           sql.NullInt32         `json:"source_port"`
	DestinationIp        sql.NullString        `json:"destination_ip"`
	DestinationPort      sql.NullInt32         `json:"destination_port"`
	SourcePrincipal      sql.NullString        `json:"source_principal"`
	SourceService        sql.NullString        `json:"source_service"`
	SourceLabels         pqtype.NullRawMessage `json:"source_labels"`
	DestinationService   sql.NullString        `json:"destination_service"`
	DestinationLabels    pqtype.NullRawMessage `json:"destination_labels"`
	RequestHttpID        sql.NullString        `json:"request_http_id"`
	Fragment             sql.NullString        `json:"fragment"`
	RequestHeaders       pqtype.NullRawMessage `json:"request_headers"`
	RequestBodySize      sql.NullInt32         `json:"request_body_size"`
	RequestBody          sql.NullString        `json:"request_body"`
	ContextExtensions    pqtype.NullRawMessage `json:"context_extensions"`
	MetadataContext      pqtype.NullRawMessage `json:"metadata_context"`
	RouteMetadataContext pqtype.NullRawMessage `json:"route_metadata_context"`
}

func (q *Queries) GetRequestLog(ctx context.Context, id int64) (GetRequestLogRow, error) {
	row := q.db.QueryRowContext(ctx, getRequestLog, id)
	var i GetRequestLogRow
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.OccurredAt,
		&i.ClientIp,
		&i.Method,
		&i.Path,
		&i.StatusCode,
		&i.Action,
		&i.RuleID,
		&i.ProfileID,
		&i.UserAgent,
		&i.Country,
		&i.LatencyMs,
		&i.RequestID,
		&i.Metadata,
		&i.Host,
		&i.Scheme,
		&i.Protocol,
		&i.Authority,
		&i.Query,
		&i.SourcePort,
		&i.DestinationIp,
		&i.DestinationPort,
		&i.SourcePrincipal,
		&i.SourceService,
		&i.SourceLabels,
		&i.DestinationService,
		&i.DestinationLabels,
		&i.RequestHttpID,
		&i.Fragment,
		&i.RequestHeaders,
		&i.RequestBodySize,
		&i.RequestBody,
		&i.ContextExtensions,
		&i.MetadataContext,
		&i.RouteMetadataContext,
	)
	return i, err
}

const listRequestLogs = `-- name: ListRequestLogs :many
SELECT id, resource_id, occurred_at, client_ip, method, path, status_code, action, rule_id, profile_id, user_agent, country, latency_ms, request_id, metadata, host, scheme, protocol, authority, query, source_port, destination_ip, destination_port, source_principal, source_service, source_labels, destination_service, destination_labels, request_http_id, fragment, request_headers, request_body_size, request_body, context_extensions, metadata_context, route_metadata_context
FROM request_logs
ORDER BY id
`

type ListRequestLogsRow struct {
	ID                   int64                 `json:"id"`
	ResourceID           sql.NullInt64         `json:"resource_id"`
	OccurredAt           time.Time             `json:"occurred_at"`
	ClientIp             string                `json:"client_ip"`
	Method               string                `json:"method"`
	Path                 string                `json:"path"`
	StatusCode           int32                 `json:"status_code"`
	Action               string                `json:"action"`
	RuleID               sql.NullInt64         `json:"rule_id"`
	ProfileID            sql.NullInt64         `json:"profile_id"`
	UserAgent            sql.NullString        `json:"user_agent"`
	Country              sql.NullString        `json:"country"`
	LatencyMs            sql.NullInt32         `json:"latency_ms"`
	RequestID            sql.NullString        `json:"request_id"`
	Metadata             pqtype.NullRawMessage `json:"metadata"`
	Host                 sql.NullString        `json:"host"`
	Scheme               sql.NullString        `json:"scheme"`
	Protocol             sql.NullString        `json:"protocol"`
	Authority            sql.NullString        `json:"authority"`
	Query                sql.NullString        `json:"query"`
	SourcePort           sql.NullInt32         `json:"source_port"`
	DestinationIp        sql.NullString        `json:"destination_ip"`
	DestinationPort      sql.NullInt32         `json:"destination_port"`
	SourcePrincipal      sql.NullString        `json:"source_principal"`
	SourceService        sql.NullString        `json:"source_service"`
	SourceLabels         pqtype.NullRawMessage `json:"source_labels"`
	DestinationService   sql.NullString        `json:"destination_service"`
	DestinationLabels    pqtype.NullRawMessage `json:"destination_labels"`
	RequestHttpID        sql.NullString        `json:"request_http_id"`
	Fragment             sql.NullString        `json:"fragment"`
	RequestHeaders       pqtype.NullRawMessage `json:"request_headers"`
	RequestBodySize      sql.NullInt32         `json:"request_body_size"`
	RequestBody          sql.NullString        `json:"request_body"`
	ContextExtensions    pqtype.NullRawMessage `json:"context_extensions"`
	MetadataContext      pqtype.NullRawMessage `json:"metadata_context"`
	RouteMetadataContext pqtype.NullRawMessage `json:"route_metadata_context"`
}

func (q *Queries) ListRequestLogs(ctx context.Context) ([]ListRequestLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRequestLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestLogsRow{}
	for rows.Next() {
		var i ListRequestLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.OccurredAt,
			&i.ClientIp,
			&i.Method,
			&i.Path,
			&i.StatusCode,
			&i.Action,
			&i.RuleID,
			&i.ProfileID,
			&i.UserAgent,
			&i.Country,
			&i.LatencyMs,
			&i.RequestID,
			&i.Metadata,
			&i.Host,
			&i.Scheme,
			&i.Protocol,
			&i.Authority,
			&i.Query,
			&i.SourcePort,
			&i.DestinationIp,
			&i.DestinationPort,
			&i.SourcePrincipal,
			&i.SourceService,
			&i.SourceLabels,
			&i.DestinationService,
			&i.DestinationLabels,
			&i.RequestHttpID,
			&i.Fragment,
			&i.RequestHeaders,
			&i.RequestBodySize,
			&i.RequestBody,
			&i.ContextExtensions,
			&i.MetadataContext,
			&i.RouteMetadataContext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
