// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: resources.sql

package db

import (
	"context"
	"database/sql"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (name, url_pattern, security_profile_id, traffic_profile_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, url_pattern, security_profile_id, traffic_profile_id, created_at, updated_at
`

type CreateResourceParams struct {
	Name              string        `json:"name"`
	UrlPattern        string        `json:"url_pattern"`
	SecurityProfileID sql.NullInt64 `json:"security_profile_id"`
	TrafficProfileID  sql.NullInt64 `json:"traffic_profile_id"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, createResource,
		arg.Name,
		arg.UrlPattern,
		arg.SecurityProfileID,
		arg.TrafficProfileID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UrlPattern,
		&i.SecurityProfileID,
		&i.TrafficProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :one
DELETE FROM resources
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteResource(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteResource, id)
	err := row.Scan(&id)
	return id, err
}

const getResource = `-- name: GetResource :one
SELECT id, name, url_pattern, security_profile_id, traffic_profile_id, created_at, updated_at
FROM resources
WHERE id = $1
`

func (q *Queries) GetResource(ctx context.Context, id int64) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResource, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UrlPattern,
		&i.SecurityProfileID,
		&i.TrafficProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResources = `-- name: ListResources :many
SELECT id, name, url_pattern, security_profile_id, traffic_profile_id, created_at, updated_at
FROM resources
ORDER BY id
`

func (q *Queries) ListResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UrlPattern,
			&i.SecurityProfileID,
			&i.TrafficProfileID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET name = $2,
    url_pattern = $3,
    security_profile_id = $4,
    traffic_profile_id = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, name, url_pattern, security_profile_id, traffic_profile_id, created_at, updated_at
`

type UpdateResourceParams struct {
	ID                int64         `json:"id"`
	Name              string        `json:"name"`
	UrlPattern        string        `json:"url_pattern"`
	SecurityProfileID sql.NullInt64 `json:"security_profile_id"`
	TrafficProfileID  sql.NullInt64 `json:"traffic_profile_id"`
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, updateResource,
		arg.ID,
		arg.Name,
		arg.UrlPattern,
		arg.SecurityProfileID,
		arg.TrafficProfileID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UrlPattern,
		&i.SecurityProfileID,
		&i.TrafficProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
