// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: security_profiles.sql

package db

import (
	"context"
	"database/sql"
)

const createSecurityProfile = `-- name: CreateSecurityProfile :one
INSERT INTO security_profiles (name, description, base_action, log_enabled, is_enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, base_action, log_enabled, is_enabled, created_at, updated_at
`

type CreateSecurityProfileParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	BaseAction  string         `json:"base_action"`
	LogEnabled  bool           `json:"log_enabled"`
	IsEnabled   bool           `json:"is_enabled"`
}

func (q *Queries) CreateSecurityProfile(ctx context.Context, arg CreateSecurityProfileParams) (SecurityProfile, error) {
	row := q.db.QueryRowContext(ctx, createSecurityProfile,
		arg.Name,
		arg.Description,
		arg.BaseAction,
		arg.LogEnabled,
		arg.IsEnabled,
	)
	var i SecurityProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BaseAction,
		&i.LogEnabled,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSecurityProfile = `-- name: DeleteSecurityProfile :one
DELETE FROM security_profiles
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteSecurityProfile(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteSecurityProfile, id)
	err := row.Scan(&id)
	return id, err
}

const getSecurityProfile = `-- name: GetSecurityProfile :one
SELECT id, name, description, base_action, log_enabled, is_enabled, created_at, updated_at
FROM security_profiles
WHERE id = $1
`

func (q *Queries) GetSecurityProfile(ctx context.Context, id int64) (SecurityProfile, error) {
	row := q.db.QueryRowContext(ctx, getSecurityProfile, id)
	var i SecurityProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BaseAction,
		&i.LogEnabled,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecurityProfiles = `-- name: ListSecurityProfiles :many
SELECT id, name, description, base_action, log_enabled, is_enabled, created_at, updated_at
FROM security_profiles
ORDER BY id
`

func (q *Queries) ListSecurityProfiles(ctx context.Context) ([]SecurityProfile, error) {
	rows, err := q.db.QueryContext(ctx, listSecurityProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecurityProfile{}
	for rows.Next() {
		var i SecurityProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.BaseAction,
			&i.LogEnabled,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecurityProfile = `-- name: UpdateSecurityProfile :one
UPDATE security_profiles
SET name = $2,
    description = $3,
    base_action = $4,
    log_enabled = $5,
    is_enabled = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, base_action, log_enabled, is_enabled, created_at, updated_at
`

type UpdateSecurityProfileParams struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	BaseAction  string         `json:"base_action"`
	LogEnabled  bool           `json:"log_enabled"`
	IsEnabled   bool           `json:"is_enabled"`
}

func (q *Queries) UpdateSecurityProfile(ctx context.Context, arg UpdateSecurityProfileParams) (SecurityProfile, error) {
	row := q.db.QueryRowContext(ctx, updateSecurityProfile,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.BaseAction,
		arg.LogEnabled,
		arg.IsEnabled,
	)
	var i SecurityProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BaseAction,
		&i.LogEnabled,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
