// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: security_rules.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const createSecurityRule = `-- name: CreateSecurityRule :one
INSERT INTO security_rules (
  profile_id,
  name,
  description,
  priority,
  rule_type,
  action,
  conditions,
  ml_model_id,
  ml_threshold,
  dry_run,
  is_enabled
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, profile_id, name, description, priority, rule_type, action, conditions, ml_model_id, ml_threshold, dry_run, is_enabled, created_at, updated_at
`

type CreateSecurityRuleParams struct {
	ProfileID   int64                 `json:"profile_id"`
	Name        string                `json:"name"`
	Description sql.NullString        `json:"description"`
	Priority    int32                 `json:"priority"`
	RuleType    string                `json:"rule_type"`
	Action      string                `json:"action"`
	Conditions  pqtype.NullRawMessage `json:"conditions"`
	MlModelID   sql.NullInt64         `json:"ml_model_id"`
	MlThreshold sql.NullInt16         `json:"ml_threshold"`
	DryRun      bool                  `json:"dry_run"`
	IsEnabled   bool                  `json:"is_enabled"`
}

type CreateSecurityRuleRow struct {
	ID          int64                 `json:"id"`
	ProfileID   int64                 `json:"profile_id"`
	Name        string                `json:"name"`
	Description sql.NullString        `json:"description"`
	Priority    int32                 `json:"priority"`
	RuleType    string                `json:"rule_type"`
	Action      string                `json:"action"`
	Conditions  pqtype.NullRawMessage `json:"conditions"`
	MlModelID   sql.NullInt64         `json:"ml_model_id"`
	MlThreshold sql.NullInt16         `json:"ml_threshold"`
	DryRun      bool                  `json:"dry_run"`
	IsEnabled   bool                  `json:"is_enabled"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

func (q *Queries) CreateSecurityRule(ctx context.Context, arg CreateSecurityRuleParams) (CreateSecurityRuleRow, error) {
	row := q.db.QueryRowContext(ctx, createSecurityRule,
		arg.ProfileID,
		arg.Name,
		arg.Description,
		arg.Priority,
		arg.RuleType,
		arg.Action,
		arg.Conditions,
		arg.MlModelID,
		arg.MlThreshold,
		arg.DryRun,
		arg.IsEnabled,
	)
	var i CreateSecurityRuleRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.Description,
		&i.Priority,
		&i.RuleType,
		&i.Action,
		&i.Conditions,
		&i.MlModelID,
		&i.MlThreshold,
		&i.DryRun,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSecurityRule = `-- name: DeleteSecurityRule :one
DELETE FROM security_rules
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteSecurityRule(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteSecurityRule, id)
	err := row.Scan(&id)
	return id, err
}

const getSecurityRule = `-- name: GetSecurityRule :one
SELECT id, profile_id, name, description, priority, rule_type, action, conditions, ml_model_id, ml_threshold, dry_run, is_enabled, created_at, updated_at
FROM security_rules
WHERE id = $1
`

type GetSecurityRuleRow struct {
	ID          int64                 `json:"id"`
	ProfileID   int64                 `json:"profile_id"`
	Name        string                `json:"name"`
	Description sql.NullString        `json:"description"`
	Priority    int32                 `json:"priority"`
	RuleType    string                `json:"rule_type"`
	Action      string                `json:"action"`
	Conditions  pqtype.NullRawMessage `json:"conditions"`
	MlModelID   sql.NullInt64         `json:"ml_model_id"`
	MlThreshold sql.NullInt16         `json:"ml_threshold"`
	DryRun      bool                  `json:"dry_run"`
	IsEnabled   bool                  `json:"is_enabled"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

func (q *Queries) GetSecurityRule(ctx context.Context, id int64) (GetSecurityRuleRow, error) {
	row := q.db.QueryRowContext(ctx, getSecurityRule, id)
	var i GetSecurityRuleRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.Description,
		&i.Priority,
		&i.RuleType,
		&i.Action,
		&i.Conditions,
		&i.MlModelID,
		&i.MlThreshold,
		&i.DryRun,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecurityRules = `-- name: ListSecurityRules :many
SELECT id, profile_id, name, description, priority, rule_type, action, conditions, ml_model_id, ml_threshold, dry_run, is_enabled, created_at, updated_at
FROM security_rules
ORDER BY id
`

type ListSecurityRulesRow struct {
	ID          int64                 `json:"id"`
	ProfileID   int64                 `json:"profile_id"`
	Name        string                `json:"name"`
	Description sql.NullString        `json:"description"`
	Priority    int32                 `json:"priority"`
	RuleType    string                `json:"rule_type"`
	Action      string                `json:"action"`
	Conditions  pqtype.NullRawMessage `json:"conditions"`
	MlModelID   sql.NullInt64         `json:"ml_model_id"`
	MlThreshold sql.NullInt16         `json:"ml_threshold"`
	DryRun      bool                  `json:"dry_run"`
	IsEnabled   bool                  `json:"is_enabled"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

func (q *Queries) ListSecurityRules(ctx context.Context) ([]ListSecurityRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSecurityRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecurityRulesRow{}
	for rows.Next() {
		var i ListSecurityRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Name,
			&i.Description,
			&i.Priority,
			&i.RuleType,
			&i.Action,
			&i.Conditions,
			&i.MlModelID,
			&i.MlThreshold,
			&i.DryRun,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecurityRule = `-- name: UpdateSecurityRule :one
UPDATE security_rules
SET profile_id = $2,
    name = $3,
    description = $4,
    priority = $5,
    rule_type = $6,
    action = $7,
    conditions = $8,
    ml_model_id = $9,
    ml_threshold = $10,
    dry_run = $11,
    is_enabled = $12,
    updated_at = now()
WHERE id = $1
RETURNING id, profile_id, name, description, priority, rule_type, action, conditions, ml_model_id, ml_threshold, dry_run, is_enabled, created_at, updated_at
`

type UpdateSecurityRuleParams struct {
	ID          int64                 `json:"id"`
	ProfileID   int64                 `json:"profile_id"`
	Name        string                `json:"name"`
	Description sql.NullString        `json:"description"`
	Priority    int32                 `json:"priority"`
	RuleType    string                `json:"rule_type"`
	Action      string                `json:"action"`
	Conditions  pqtype.NullRawMessage `json:"conditions"`
	MlModelID   sql.NullInt64         `json:"ml_model_id"`
	MlThreshold sql.NullInt16         `json:"ml_threshold"`
	DryRun      bool                  `json:"dry_run"`
	IsEnabled   bool                  `json:"is_enabled"`
}

type UpdateSecurityRuleRow struct {
	ID          int64                 `json:"id"`
	ProfileID   int64                 `json:"profile_id"`
	Name        string                `json:"name"`
	Description sql.NullString        `json:"description"`
	Priority    int32                 `json:"priority"`
	RuleType    string                `json:"rule_type"`
	Action      string                `json:"action"`
	Conditions  pqtype.NullRawMessage `json:"conditions"`
	MlModelID   sql.NullInt64         `json:"ml_model_id"`
	MlThreshold sql.NullInt16         `json:"ml_threshold"`
	DryRun      bool                  `json:"dry_run"`
	IsEnabled   bool                  `json:"is_enabled"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

func (q *Queries) UpdateSecurityRule(ctx context.Context, arg UpdateSecurityRuleParams) (UpdateSecurityRuleRow, error) {
	row := q.db.QueryRowContext(ctx, updateSecurityRule,
		arg.ID,
		arg.ProfileID,
		arg.Name,
		arg.Description,
		arg.Priority,
		arg.RuleType,
		arg.Action,
		arg.Conditions,
		arg.MlModelID,
		arg.MlThreshold,
		arg.DryRun,
		arg.IsEnabled,
	)
	var i UpdateSecurityRuleRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.Description,
		&i.Priority,
		&i.RuleType,
		&i.Action,
		&i.Conditions,
		&i.MlModelID,
		&i.MlThreshold,
		&i.DryRun,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
