// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: traffic_rules.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createTrafficRule = `-- name: CreateTrafficRule :one
INSERT INTO traffic_rules (
  profile_id,
  name,
  description,
  priority,
  dry_run,
  match_all,
  requests_limit,
  period_seconds,
  conditions,
  is_enabled
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, profile_id, name, description, priority, dry_run, match_all, requests_limit, period_seconds, conditions, is_enabled, created_at, updated_at
`

type CreateTrafficRuleParams struct {
	ProfileID     int64                 `json:"profile_id"`
	Name          string                `json:"name"`
	Description   sql.NullString        `json:"description"`
	Priority      int32                 `json:"priority"`
	DryRun        bool                  `json:"dry_run"`
	MatchAll      bool                  `json:"match_all"`
	RequestsLimit int32                 `json:"requests_limit"`
	PeriodSeconds int32                 `json:"period_seconds"`
	Conditions    pqtype.NullRawMessage `json:"conditions"`
	IsEnabled     bool                  `json:"is_enabled"`
}

func (q *Queries) CreateTrafficRule(ctx context.Context, arg CreateTrafficRuleParams) (TrafficRule, error) {
	row := q.db.QueryRowContext(ctx, createTrafficRule,
		arg.ProfileID,
		arg.Name,
		arg.Description,
		arg.Priority,
		arg.DryRun,
		arg.MatchAll,
		arg.RequestsLimit,
		arg.PeriodSeconds,
		arg.Conditions,
		arg.IsEnabled,
	)
	var i TrafficRule
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.Description,
		&i.Priority,
		&i.DryRun,
		&i.MatchAll,
		&i.RequestsLimit,
		&i.PeriodSeconds,
		&i.Conditions,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTrafficRule = `-- name: DeleteTrafficRule :one
DELETE FROM traffic_rules
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteTrafficRule(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteTrafficRule, id)
	err := row.Scan(&id)
	return id, err
}

const getTrafficRule = `-- name: GetTrafficRule :one
SELECT id, profile_id, name, description, priority, dry_run, match_all, requests_limit, period_seconds, conditions, is_enabled, created_at, updated_at
FROM traffic_rules
WHERE id = $1
`

func (q *Queries) GetTrafficRule(ctx context.Context, id int64) (TrafficRule, error) {
	row := q.db.QueryRowContext(ctx, getTrafficRule, id)
	var i TrafficRule
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.Description,
		&i.Priority,
		&i.DryRun,
		&i.MatchAll,
		&i.RequestsLimit,
		&i.PeriodSeconds,
		&i.Conditions,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTrafficRules = `-- name: ListTrafficRules :many
SELECT id, profile_id, name, description, priority, dry_run, match_all, requests_limit, period_seconds, conditions, is_enabled, created_at, updated_at
FROM traffic_rules
ORDER BY id
`

func (q *Queries) ListTrafficRules(ctx context.Context) ([]TrafficRule, error) {
	rows, err := q.db.QueryContext(ctx, listTrafficRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrafficRule{}
	for rows.Next() {
		var i TrafficRule
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Name,
			&i.Description,
			&i.Priority,
			&i.DryRun,
			&i.MatchAll,
			&i.RequestsLimit,
			&i.PeriodSeconds,
			&i.Conditions,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrafficRule = `-- name: UpdateTrafficRule :one
UPDATE traffic_rules
SET profile_id = $2,
    name = $3,
    description = $4,
    priority = $5,
    dry_run = $6,
    match_all = $7,
    requests_limit = $8,
    period_seconds = $9,
    conditions = $10,
    is_enabled = $11,
    updated_at = now()
WHERE id = $1
RETURNING id, profile_id, name, description, priority, dry_run, match_all, requests_limit, period_seconds, conditions, is_enabled, created_at, updated_at
`

type UpdateTrafficRuleParams struct {
	ID            int64                 `json:"id"`
	ProfileID     int64                 `json:"profile_id"`
	Name          string                `json:"name"`
	Description   sql.NullString        `json:"description"`
	Priority      int32                 `json:"priority"`
	DryRun        bool                  `json:"dry_run"`
	MatchAll      bool                  `json:"match_all"`
	RequestsLimit int32                 `json:"requests_limit"`
	PeriodSeconds int32                 `json:"period_seconds"`
	Conditions    pqtype.NullRawMessage `json:"conditions"`
	IsEnabled     bool                  `json:"is_enabled"`
}

func (q *Queries) UpdateTrafficRule(ctx context.Context, arg UpdateTrafficRuleParams) (TrafficRule, error) {
	row := q.db.QueryRowContext(ctx, updateTrafficRule,
		arg.ID,
		arg.ProfileID,
		arg.Name,
		arg.Description,
		arg.Priority,
		arg.DryRun,
		arg.MatchAll,
		arg.RequestsLimit,
		arg.PeriodSeconds,
		arg.Conditions,
		arg.IsEnabled,
	)
	var i TrafficRule
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.Description,
		&i.Priority,
		&i.DryRun,
		&i.MatchAll,
		&i.RequestsLimit,
		&i.PeriodSeconds,
		&i.Conditions,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
