// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: traffic_profiles.sql

package db

import (
	"context"
	"database/sql"
)

const createTrafficProfile = `-- name: CreateTrafficProfile :one
INSERT INTO traffic_profiles (name, description, is_enabled)
VALUES ($1, $2, $3)
RETURNING id, name, description, is_enabled, created_at, updated_at
`

type CreateTrafficProfileParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsEnabled   bool           `json:"is_enabled"`
}

func (q *Queries) CreateTrafficProfile(ctx context.Context, arg CreateTrafficProfileParams) (TrafficProfile, error) {
	row := q.db.QueryRowContext(ctx, createTrafficProfile, arg.Name, arg.Description, arg.IsEnabled)
	var i TrafficProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTrafficProfile = `-- name: DeleteTrafficProfile :one
DELETE FROM traffic_profiles
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteTrafficProfile(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteTrafficProfile, id)
	err := row.Scan(&id)
	return id, err
}

const getTrafficProfile = `-- name: GetTrafficProfile :one
SELECT id, name, description, is_enabled, created_at, updated_at
FROM traffic_profiles
WHERE id = $1
`

func (q *Queries) GetTrafficProfile(ctx context.Context, id int64) (TrafficProfile, error) {
	row := q.db.QueryRowContext(ctx, getTrafficProfile, id)
	var i TrafficProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTrafficProfiles = `-- name: ListTrafficProfiles :many
SELECT id, name, description, is_enabled, created_at, updated_at
FROM traffic_profiles
ORDER BY id
`

func (q *Queries) ListTrafficProfiles(ctx context.Context) ([]TrafficProfile, error) {
	rows, err := q.db.QueryContext(ctx, listTrafficProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrafficProfile{}
	for rows.Next() {
		var i TrafficProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrafficProfile = `-- name: UpdateTrafficProfile :one
UPDATE traffic_profiles
SET name = $2,
    description = $3,
    is_enabled = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, is_enabled, created_at, updated_at
`

type UpdateTrafficProfileParams struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsEnabled   bool           `json:"is_enabled"`
}

func (q *Queries) UpdateTrafficProfile(ctx context.Context, arg UpdateTrafficProfileParams) (TrafficProfile, error) {
	row := q.db.QueryRowContext(ctx, updateTrafficProfile,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsEnabled,
	)
	var i TrafficProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
